//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtCaseManagement.ApplicationCore.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messaging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messaging() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourtCaseManagement.ApplicationCore.Messages.Messaging", typeof(Messaging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DistributionDateGreaterThanTheCurrentDate.
        /// </summary>
        public static string DistributionDateGreaterThanTheCurrentDate {
            get {
                return ResourceManager.GetString("DistributionDateGreaterThanTheCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DoubleUnifiedProcessNumber.
        /// </summary>
        public static string DoubleUnifiedProcessNumber {
            get {
                return ResourceManager.GetString("DoubleUnifiedProcessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DuplicateResponsible.
        /// </summary>
        public static string DuplicateResponsible {
            get {
                return ResourceManager.GetString("DuplicateResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ExceededLimitOfHierarchyLinkedProcessId.
        /// </summary>
        public static string ExceededLimitOfHierarchyLinkedProcessId {
            get {
                return ResourceManager.GetString("ExceededLimitOfHierarchyLinkedProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ExceededLimitOfHierarchyResponsible.
        /// </summary>
        public static string ExceededLimitOfHierarchyResponsible {
            get {
                return ResourceManager.GetString("ExceededLimitOfHierarchyResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ExceededLimitOfResponsible.
        /// </summary>
        public static string ExceededLimitOfResponsible {
            get {
                return ResourceManager.GetString("ExceededLimitOfResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ExceededMaximumValue.
        /// </summary>
        public static string ExceededMaximumValue {
            get {
                return ResourceManager.GetString("ExceededMaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FixedSizeUnifiedProcessNumber.
        /// </summary>
        public static string FixedSizeUnifiedProcessNumber {
            get {
                return ResourceManager.GetString("FixedSizeUnifiedProcessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InvalidCPF.
        /// </summary>
        public static string InvalidCPF {
            get {
                return ResourceManager.GetString("InvalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InvalidProcessId.
        /// </summary>
        public static string InvalidProcessId {
            get {
                return ResourceManager.GetString("InvalidProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InvalidResponsible.
        /// </summary>
        public static string InvalidResponsible {
            get {
                return ResourceManager.GetString("InvalidResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InvalidSituationId.
        /// </summary>
        public static string InvalidSituationId {
            get {
                return ResourceManager.GetString("InvalidSituationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MaximumSizeClientPhysicalFolder.
        /// </summary>
        public static string MaximumSizeClientPhysicalFolder {
            get {
                return ResourceManager.GetString("MaximumSizeClientPhysicalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MaximumSizeDescription.
        /// </summary>
        public static string MaximumSizeDescription {
            get {
                return ResourceManager.GetString("MaximumSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MaximumSizeMail.
        /// </summary>
        public static string MaximumSizeMail {
            get {
                return ResourceManager.GetString("MaximumSizeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MaximumSizeName.
        /// </summary>
        public static string MaximumSizeName {
            get {
                return ResourceManager.GetString("MaximumSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NotFoundProcess.
        /// </summary>
        public static string NotFoundProcess {
            get {
                return ResourceManager.GetString("NotFoundProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NotFoundResponsible.
        /// </summary>
        public static string NotFoundResponsible {
            get {
                return ResourceManager.GetString("NotFoundResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NotNull.
        /// </summary>
        public static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RegistrationCannotBeEdited.
        /// </summary>
        public static string RegistrationCannotBeEdited {
            get {
                return ResourceManager.GetString("RegistrationCannotBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredCpf.
        /// </summary>
        public static string RequiredCpf {
            get {
                return ResourceManager.GetString("RequiredCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredJusticeSecret.
        /// </summary>
        public static string RequiredJusticeSecret {
            get {
                return ResourceManager.GetString("RequiredJusticeSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredMail.
        /// </summary>
        public static string RequiredMail {
            get {
                return ResourceManager.GetString("RequiredMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredName.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredPage.
        /// </summary>
        public static string RequiredPage {
            get {
                return ResourceManager.GetString("RequiredPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredPhotograph.
        /// </summary>
        public static string RequiredPhotograph {
            get {
                return ResourceManager.GetString("RequiredPhotograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredProcessId.
        /// </summary>
        public static string RequiredProcessId {
            get {
                return ResourceManager.GetString("RequiredProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredResponsibles.
        /// </summary>
        public static string RequiredResponsibles {
            get {
                return ResourceManager.GetString("RequiredResponsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredSituationId.
        /// </summary>
        public static string RequiredSituationId {
            get {
                return ResourceManager.GetString("RequiredSituationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RequiredUnifiedProcessNumber.
        /// </summary>
        public static string RequiredUnifiedProcessNumber {
            get {
                return ResourceManager.GetString("RequiredUnifiedProcessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UnexpectedError.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
