version: '3.4'

services:
  court-case-management-postgres:
    container_name: CourtCaseManagement_Postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - court-case-management-network

  court-case-management-pgadmin:
    container_name: CourtCaseManagement_PgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "thiagoautran@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16544:80"
    depends_on:
      - court-case-management-postgres
    networks:
      - court-case-management-network

  courtcasemanagement.api:
    container_name: CourtCaseManagement_WebApi
    image: ${DOCKER_REGISTRY-}courtcasemanagementapi
    build:
      context: .
      dockerfile: CourtCaseManagement.Api/Dockerfile
    ports:
      - "44360:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=host=court-case-management-postgres;port=5432;database=postgres;username=postgres;password=admin;
    depends_on:
      - court-case-management-postgres
      - court-case-management-pgadmin
    networks:
      - court-case-management-network

networks: 
  court-case-management-network:
    driver: bridge