// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.3.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CourtCaseManagement.Test.Process
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Atualizar Processos")]
    public partial class AtualizarProcessosFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "UpdateAsync.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Atualizar Processos", "\tPara quanto precisar atualizar um processo\r\n\tEnquanto funcionario\r\n\tEu gostaria " +
                    "de atualizar os dados de um processo", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Atualizar um processo")]
        [NUnit.Framework.CategoryAttribute("ProcessUpdateAsync")]
        [NUnit.Framework.TestCaseAttribute("\"3513038-00.2016.8.23.0024\"", "\"2020-09-17\"", "\"N\"", "\"D\"", "\"teste 2\"", "\"Em andamento\"", "\"303.951.780-53\"", "\"Nicolas Thales Carlos Moraes\"", "\"nicolas@gmail.com\"", "\"teste\"", null)]
        public virtual void AtualizarUmProcesso(string unifiedProcessNumber, string distributionDate, string justiceSecret, string clientPhysicalFolder, string description, string situationId, string responsiblesCpf, string responsiblesName, string responsiblesEMail, string image, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ProcessUpdateAsync"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("unifiedProcessNumber", unifiedProcessNumber);
            argumentsOfScenario.Add("distributionDate", distributionDate);
            argumentsOfScenario.Add("justiceSecret", justiceSecret);
            argumentsOfScenario.Add("clientPhysicalFolder", clientPhysicalFolder);
            argumentsOfScenario.Add("description", description);
            argumentsOfScenario.Add("situationId", situationId);
            argumentsOfScenario.Add("responsiblesCpf", responsiblesCpf);
            argumentsOfScenario.Add("responsiblesName", responsiblesName);
            argumentsOfScenario.Add("responsiblesEMail", responsiblesEMail);
            argumentsOfScenario.Add("image", image);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar um processo", null, tagsOfScenario, argumentsOfScenario);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "unifiedProcessNumber",
                            "distributionDate",
                            "justiceSecret",
                            "clientPhysicalFolder",
                            "description",
                            "situationId",
                            "responsiblesCpf",
                            "responsiblesName",
                            "responsiblesEMail",
                            "image"});
                table2.AddRow(new string[] {
                            "\"3513038-00.2016.8.23.0023\"",
                            "\"2020-10-07\"",
                            "\"S\"",
                            "\"C\"",
                            "\"teste 1\"",
                            "\"Em andamento\"",
                            "\"237.958.172-00\"",
                            "\"Nicolas Thales Carlos Moraes\"",
                            "\"nicolas@gmail.com\"",
                            "\"teste\""});
#line 10
 testRunner.Given("o processo previamente cadastrado", ((string)(null)), table2, "Dado ");
#line hidden
#line 13
 testRunner.And(string.Format("atualizando o número do processo unificado {0}", unifiedProcessNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 14
 testRunner.And(string.Format("atualizando a data de distribuição para {0}", distributionDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
 testRunner.And(string.Format("atualizando o segredo de justiça para {0}", justiceSecret), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
 testRunner.And(string.Format("atualizando a pasta física cliente para {0}", clientPhysicalFolder), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
 testRunner.And(string.Format("atualizando a descrição para {0}", description), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 18
 testRunner.And(string.Format("atualizando a situação para {0}", situationId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 19
 testRunner.And(string.Format("atualizando o responsavel {0} {1} {2} {3}", responsiblesCpf, responsiblesName, responsiblesEMail, image), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 20
 testRunner.When("solicitar o atualizar um processo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 21
 testRunner.Then("o sistema retornara o código 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Atualizar um processo sem informar todos os campos obrigatórios")]
        [NUnit.Framework.CategoryAttribute("ProcessUpdateAsync")]
        [NUnit.Framework.TestCaseAttribute("\"3513038-00.2016.8.23.0023\"", "\"2020-10-07\"", "\"S\"", "\"C\"", "\"teste 1\"", "\"Em andamento\"", "\"\"", "\"Nicolas Thales Carlos Moraes\"", "\"nicolas@gmail.com\"", "\"teste\"", "\"RequiredResponsibles\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"\"", "\"\"", "\"N\"", "\"\"", "\"\"", "\"Desmembrado\"", "\"\"", "\"Nicolas Thales Carlos Moraes\"", "\"nicolas@gmail.com\"", "\"teste\"", "\"RequiredResponsibles;RequiredUnifiedProcessNumber\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"\"", "\"\"", "\"\"", "\"\"", "\"\"", "\"Desmembrado\"", "\"\"", "\"Nicolas Thales Carlos Moraes\"", "\"nicolas@gmail.com\"", "\"teste\"", "\"RequiredResponsibles;RequiredUnifiedProcessNumber;RequiredJusticeSecret\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"\"", "\"\"", "\"\"", "\"\"", "\"\"", "\"\"", "\"\"", "\"Nicolas Thales Carlos Moraes\"", "\"nicolas@gmail.com\"", "\"teste\"", "\"RequiredResponsibles;RequiredUnifiedProcessNumber;RequiredJusticeSecret;Required" +
            "SituationId\"", null)]
        public virtual void AtualizarUmProcessoSemInformarTodosOsCamposObrigatorios(string unifiedProcessNumber, string distributionDate, string justiceSecret, string clientPhysicalFolder, string description, string situationId, string responsiblesCpf, string responsiblesName, string responsiblesEMail, string image, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ProcessUpdateAsync"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("unifiedProcessNumber", unifiedProcessNumber);
            argumentsOfScenario.Add("distributionDate", distributionDate);
            argumentsOfScenario.Add("justiceSecret", justiceSecret);
            argumentsOfScenario.Add("clientPhysicalFolder", clientPhysicalFolder);
            argumentsOfScenario.Add("description", description);
            argumentsOfScenario.Add("situationId", situationId);
            argumentsOfScenario.Add("responsiblesCpf", responsiblesCpf);
            argumentsOfScenario.Add("responsiblesName", responsiblesName);
            argumentsOfScenario.Add("responsiblesEMail", responsiblesEMail);
            argumentsOfScenario.Add("image", image);
            argumentsOfScenario.Add("messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar um processo sem informar todos os campos obrigatórios", null, tagsOfScenario, argumentsOfScenario);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "unifiedProcessNumber",
                            "distributionDate",
                            "justiceSecret",
                            "clientPhysicalFolder",
                            "description",
                            "situationId",
                            "responsiblesCpf",
                            "responsiblesName",
                            "responsiblesEMail",
                            "image"});
                table3.AddRow(new string[] {
                            "\"3513038-00.2016.8.23.0023\"",
                            "\"2020-10-07\"",
                            "\"S\"",
                            "\"C\"",
                            "\"teste 1\"",
                            "\"Em andamento\"",
                            "\"237.958.172-00\"",
                            "\"Nicolas Thales Carlos Moraes\"",
                            "\"nicolas@gmail.com\"",
                            "\"teste\""});
#line 29
 testRunner.Given("o processo previamente cadastrado", ((string)(null)), table3, "Dado ");
#line hidden
#line 32
 testRunner.And(string.Format("atualizando o número do processo unificado {0}", unifiedProcessNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 33
 testRunner.And(string.Format("atualizando a data de distribuição para {0}", distributionDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 34
 testRunner.And(string.Format("atualizando o segredo de justiça para {0}", justiceSecret), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 35
 testRunner.And(string.Format("atualizando a pasta física cliente para {0}", clientPhysicalFolder), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 36
 testRunner.And(string.Format("atualizando a descrição para {0}", description), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 37
 testRunner.And(string.Format("atualizando a situação para {0}", situationId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 38
 testRunner.And(string.Format("atualizando o responsavel {0} {1} {2} {3}", responsiblesCpf, responsiblesName, responsiblesEMail, image), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 39
 testRunner.When("solicitar o atualizar um processo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 40
 testRunner.Then("o sistema retornara o código 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 41
 testRunner.And(string.Format("apresentara os seguintes codigo de erros {0}", messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
