// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.3.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CourtCaseManagement.Test.Responsible
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Atualizar Responsável")]
    public partial class AtualizarResponsavelFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "UpdateAsync.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Atualizar Responsável", "\tPara quanto precisar atualizar um responsável\r\n\tEnquanto funcionario\r\n\tEu gostar" +
                    "ia de atualizar os dados de um responsável", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Atualizar um responsável")]
        [NUnit.Framework.CategoryAttribute("ResponsibleUpdateAsync")]
        [NUnit.Framework.TestCaseAttribute("\"303.951.780-53\"", "\"Nicolas Thales Carlos Moraes\"", "\"nicolas@gmail.com\"", "\"teste\"", null)]
        public virtual void AtualizarUmResponsavel(string responsiblesCpf, string responsiblesName, string responsiblesEMail, string image, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ResponsibleUpdateAsync"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("responsiblesCpf", responsiblesCpf);
            argumentsOfScenario.Add("responsiblesName", responsiblesName);
            argumentsOfScenario.Add("responsiblesEMail", responsiblesEMail);
            argumentsOfScenario.Add("image", image);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar um responsável", null, tagsOfScenario, argumentsOfScenario);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "responsiblesName",
                            "responsiblesEMail",
                            "image",
                            "responsiblesCpf"});
                table5.AddRow(new string[] {
                            "\"Nicolas Thales Carlos Moraes\"",
                            "\"nicolas@gmail.com\"",
                            "\"teste\"",
                            "\"237.958.172-00\""});
#line 10
 testRunner.Given("um responsável previamente cadastrado", ((string)(null)), table5, "Dado ");
#line hidden
#line 13
 testRunner.And(string.Format("atualizando o cpf para {0}", responsiblesCpf), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 14
 testRunner.And(string.Format("atualizando o nome para {0}", responsiblesName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
 testRunner.And(string.Format("atualizando o e-mail para {0}", responsiblesEMail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
 testRunner.And(string.Format("atualizando a foto para {0}", image), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 17
 testRunner.When("solicitar o atualizar um responsável", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 18
 testRunner.Then("o sistema retornara o código 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Atualizar um responsável sem informar todos os campos obrigatórios")]
        [NUnit.Framework.CategoryAttribute("ResponsibleUpdateAsync")]
        [NUnit.Framework.TestCaseAttribute("\"\"", "\"Nicolas Thales Carlos Moraes\"", "\"nicolas@gmail.com\"", "\"teste\"", "\"RequiredCpf\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"\"", "\"\"", "\"nicolas@gmail.com\"", "\"teste\"", "\"RequiredCpf;RequiredName\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"\"", "\"\"", "\"\"", "\"teste\"", "\"RequiredCpf;RequiredName;RequiredMail\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"\"", "\"\"", "\"\"", "\"\"", "\"RequiredCpf;RequiredName;RequiredMail;RequiredPhotograph\"", null)]
        public virtual void AtualizarUmResponsavelSemInformarTodosOsCamposObrigatorios(string responsiblesCpf, string responsiblesName, string responsiblesEMail, string image, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ResponsibleUpdateAsync"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("responsiblesCpf", responsiblesCpf);
            argumentsOfScenario.Add("responsiblesName", responsiblesName);
            argumentsOfScenario.Add("responsiblesEMail", responsiblesEMail);
            argumentsOfScenario.Add("image", image);
            argumentsOfScenario.Add("messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar um responsável sem informar todos os campos obrigatórios", null, tagsOfScenario, argumentsOfScenario);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "responsiblesCpf",
                            "responsiblesName",
                            "responsiblesEMail",
                            "image"});
                table6.AddRow(new string[] {
                            "\"237.958.172-00\"",
                            "\"Nicolas Thales Carlos Moraes\"",
                            "\"nicolas@gmail.com\"",
                            "\"teste\""});
#line 26
 testRunner.Given("um responsável previamente cadastrado", ((string)(null)), table6, "Dado ");
#line hidden
#line 29
 testRunner.And(string.Format("atualizando o cpf para {0}", responsiblesCpf), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 30
 testRunner.And(string.Format("atualizando o nome para {0}", responsiblesName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 31
 testRunner.And(string.Format("atualizando o e-mail para {0}", responsiblesEMail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 32
 testRunner.And(string.Format("atualizando a foto para {0}", image), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 33
 testRunner.When("solicitar o atualizar um responsável", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 34
 testRunner.Then("o sistema retornara o código 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 35
 testRunner.And(string.Format("apresentara os seguintes codigo de erros {0}", messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
